---
services:
  yggtorrent-exporter:
    image: louisgrasset/yggtorrent-exporter:latest
    container_name: yggtorrent-exporter
    restart: always
    ports:
      - "3000:3000"
    environment:
      - YGG_PROFILE_URL=${YGG_PROFILE_URL} #https://www.ygg.re/user/account
      - YGG_USER_AGENT=${YGG_USER_AGENT}
      - YGG_COOKIE=${YGG_COOKIE}
