version: '3.8'

services:
  yggtorrent-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - YGG_PROFILE_URL= "" # "https://www3.yggtorrent.xxxxx/profile/xxxxxx-xxxxx"
      - FLARESOLVERR_URL= "" # "http://flaresolverr:8191"
